language: python
python:
- 2.7
before_install:
- openssl aes-256-cbc -K $encrypted_8f2e1fe0e7f3_key -iv $encrypted_8f2e1fe0e7f3_iv -in sims-key.enc -out sims-key -d
install:
- chmod 600 sims-key
- eval `ssh-agent -s`
- ssh-add sims-key
- ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@104.236.155.138 'bash -s' < remote.sh
- source ./prepare.sh
script:
- df -kh .
- bash sims-maf.sh
