language: python
python:
- 2.7
install:
- echo $TRAVIS_PULL_REQUEST
- NOTEBOOKS="tutorials"
- d=`TZ=":US/Pacific" date +%y-%m-%d----%H:%M:%S`
script:
- df -kh .
- source ./scripts/prepare.sh
- export PATH="$PWD/miniconda/bin:$PATH"
- source ./scripts/setup-sims.sh
- source ./scripts/getfiles.sh
- source ./scripts/runipy.sh
after_deploy:
- exit $ERROR
deploy:
  provider: s3
  access_key_id: AKIAJF3H4NKNLZHNHKWA
  secret_access_key:
    secure: NqlQQtvLXi6F+NPT4Yf7bqEK0cL3hixwFTUwfiIdA42dLFBn05mmaaoEErJre087NHQON32lmgTXagZZdja8PNW2tnl2UiQ6TTdqtFZIGsXsahBcZvgx82bz7RffN+wkm8Hes4lBdKs3eFzJ9pdS53BgFhYq2vQxmGuHt1/w3LEKLxQIfdc7LRGiDz/39EXsFhPfKqGI0OvpAfm4KE45wnWBGLpFDxu97B+THu4geaiEAvZCmsfpeYMZxTt1vytC0P6llklaKXj6qYGw4qtnzglw5MRCDt2/1zhDuR7CWEDa4Ss4dxRVQZx4Tx1qHkbwgcb9pgK9RtntCG+Vul0j8gJQJtOLkMmcehy3mS1DBYsgLi9hPxQgAZ5r1+wPdLmHtlX9wxGA1Vx5Ul0JQ27svWlswhNNm4VsoLon2GI8yBGJfy4q1JbNz3q5iOWBHiM5WmhHP4QD/5JyNdrxGbp1emMZnrDQNAdwAy3/bKy2KvLzG0tXOW6JNRPWHGcH+26w62UtypwlFPdQvUGcF5uDsICG492vqEpTlXAXr9050V0+qkE60o4Jyun8HUPP+NJU056thOV4m4LuwKFOBW44SgB9VJSuH78f8NR+J8axnZmlxZSs8YHzczEUzlcU2hHc/v16TfOtcu5FBJDytqvFCDXje5OgegPrsNZMTKt3xsA=
  bucket: sims-maf-contrib
  local-dir: fails
  upload-dir: "$d"
  on:
    repo: marcusbooyah/sims_maf_contrib
    branch: all
